# Generated by Django 6.0.1 on 2026-03-28 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='verification_code',
            field=models.UUIDField(blank=True, default=uuid.uuid1, editable=False, null=True),
        ),
    ]
