# Generated by Django 6.0.1 on 2026-03-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
