# Generated by Django 6.0.1 on 2026-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='year_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='year_start',
            field=models.DateField(),
        ),
    ]
