# Generated by Django 6.0.1 on 2026-02-10 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('UID', models.UUIDField(default=uuid.uuid8, editable=False, primary_key=True, serialize=False)),
                ('quarter_number', models.PositiveSmallIntegerField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('UID', models.UUIDField(default=uuid.uuid8, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='accounts.quarter'),
        ),
        migrations.AddField(
            model_name='quarter',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_year', to='accounts.schoolyear'),
        ),
    ]
