# Generated by Django 6.0.1 on 2026-03-28 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lessonplan_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='verification_code',
            field=models.UUIDField(blank=True, default=uuid.uuid1, editable=False, null=True, unique=True),
        ),
    ]
