# Generated by Django 6.0.1 on 2026-02-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_quarter_schoolyear_alter_lessonplan_quarter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarter',
            old_name='UID',
            new_name='quarter_id',
        ),
        migrations.RenameField(
            model_name='schoolyear',
            old_name='UID',
            new_name='year_id',
        ),
    ]
