# Generated by Django 6.0.1 on 2026-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_schoolyear_year_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='reviewed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reviewedlessonplan',
            name='reviewed_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
