# Generated by Django 6.0.1 on 2026-03-23 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lessonplan_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid1, editable=False, null=True),
        ),
    ]
