# Generated by Django 6.0.1 on 2026-01-22 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_middle_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid8, editable=False, primary_key=True, serialize=False)),
                ('lesson_plan', models.FileField(upload_to='pdfs')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
