# Generated by Django 6.0.1 on 2026-01-23 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lessonplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='User',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='quarter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pictures'),
        ),
    ]
