# Generated by Django 6.0.1 on 2026-03-23 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lessonplan_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
