# Generated by Django 6.0.1 on 2026-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_lessonplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quarter',
            unique_together={('school_year', 'quarter_number')},
        ),
    ]
