# Generated by Django 6.0.1 on 2026-02-18 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_uid_quarter_quarter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='quarter',
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='plan_id',
            field=models.UUIDField(default=uuid.uuid8, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewedlessonplan',
            name='review_id',
            field=models.UUIDField(default=uuid.uuid8, editable=False, primary_key=True, serialize=False),
        ),
    ]
