# Generated by Django 6.0.1 on 2026-01-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_lessonplan_user_lessonplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Teacher', max_length=20),
        ),
    ]
