# Generated by Django 6.0.1 on 2026-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_quarter_school_year_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
