# Generated by Django 6.0.1 on 2026-02-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_lessonplan_quarter_alter_lessonplan_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='quarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='accounts.quarter'),
            preserve_default=False,
        ),
    ]
