# Generated by Django 6.0.1 on 2026-03-23 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_lessonplan_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='verification_code',
            field=models.UUIDField(blank=True, default=uuid.uuid1, editable=False, null=True),
        ),
    ]
