# Generated by Django 6.0.1 on 2026-01-27 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='ReviewedLessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
